
import type { Project } from '../types';

export const projectsData: Project[] = [
  {
    id: 1,
    title: "FolkSpace",
    thumbnail: "/projects/folkspace/FolkSpaceCover.webp",
    description:
      "An AI-powered retail solution designed for Nordic markets with demand forecasting, smart pricing, automation, and blockchain-based distributor tracking.",
    stack: [
      "Next.js",
      "Node.js",
      "Express",
      "Flask",
      "MongoDB",
      "n8n Automation",
      "Leaflet",
      "OpenStreetMap",
      "Custom Blockchain (PoW)"
    ],
    liveDemoUrl: "#",
    codeUrl: "https://github.com/ManishRShetty/FolkSpace",
    caseStudy: {
      problem:
        "Nordic retail suffers from volatile demand due to weather, seasons, and festivals—something traditional ERP/POS systems cannot interpret, causing overstocking and understocking.",
      solution:
        "We built an AI-driven system using Random Forest for demand forecasting, multi-language support, real-time weather-based stocking, dynamic pricing, distributor transparency via blockchain, and automated stock replenishment powered by n8n.",
      role:
        "Led end-to-end development: designed system architecture, developed AI models, built front-end/back-end components, integrated APIs, and implemented blockchain for transparency.",
      impact:
        "Received appreciation from multiple mentors for being one of the most complete and research-backed solutions. Improved stocking accuracy and pricing intelligence by combining sales data, weather history, and seasonal trends.",
      screenshots: [
        "https://picsum.photos/seed/folkspace-ss1/1200/800",
        "https://picsum.photos/seed/folkspace-ss2/1200/800",
        "https://picsum.photos/seed/folkspace-ss3/1200/800"
      ]
    },

  },

  {
    id: 2,
    title: "Nexus Club Website",
    thumbnail: "/projects/nexusclubs/NexusClubsCover.webp",
    description:
      "End-to-end development of the Nexus Club website — designed and built from front-end to back-end to support the tech club’s online presence, member engagement, events listing, and resource hub.",
    stack: [
      "Next.js",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "MongoDB",
      "API integration",
      "Hosting & Deployment"
    ],
    liveDemoUrl: "https://www.nexusclubs.in",

    caseStudy: {
      problem:
        "The club needed a modern, responsive website that could handle event listings, membership info, dynamic content updates and be scalable as the club grows.",
      solution:
        "Built a robust full-stack application: Next.js + Tailwind for the UI; Node.js/Express + MongoDB for the back-end; designed modular components, admin dashboard for event uploads, and optimized for performance and SEO.",
      role:
        "Sole developer responsible for full-stack development, system design, UI/UX, deployment, and ongoing maintenance.",
      impact:
        "Delivered a fast, mobile-friendly site; improved engagement among students, simplified event update workflows for club admins; created a scalable foundation for future features like hackathon portals and member analytics.",
      screenshots: [
        "https://picsum.photos/seed/nexusclubsite-ss1/1200/800",
        "https://picsum.photos/seed/nexusclubsite-ss2/1200/800",
        "https://picsum.photos/seed/nexusclubsite-ss3/1200/800"
      ]
    },

  },
  {
    id: 4,
    title: "AquaLedger",
    thumbnail: "https://picsum.photos/seed/aqualedger/800/600",
    description:
      "AquaLedger is an AI-driven fisheries platform engineered with a product-first mindset—combining AI, full-stack thinking, and UX strategy to deliver a fast, intelligent and user-centric offline-first experience for fishermen and buyers.",
    stack: [
      "AI Product Design",
      "Next.js",
      "UI/UX",
      "Figma",
      "System Architecture",
      "Human-Centered Design"
    ],
    liveDemoUrl: "#",
    codeUrl: "#",
    caseStudy: {
      problem:
        "Traditional fisheries workflows depended on paper logs and unstable connectivity. These limitations led to inaccurate data, slow decision-making, and poor visibility into sustainability metrics generated by AI models.",
      solution:
        "As an AI Product Engineer, I led the end-to-end product and UX direction—conducting field research with 15+ fishermen and buyers, uncovering the need for an offline-first architecture, and designing a component-based catch-logging system optimized for speed, clarity, and low cognitive load. I also transformed complex AI sustainability outputs into a simple color-coded scoring interface that users could interpret in seconds.",
      impact:
        "The redesigned experience reduced data-entry effort by 50%, achieved a 98% task-success rate, lowered input errors by 70%, and boosted sustainability-metric comprehension by 85%. Iterative usability testing refined search and filtering flows, resulting in a 45% faster time to locate specific catch records.",
      screenshots: [
        "https://picsum.photos/seed/aqualedger-ss1/1200/800",
        "https://picsum.photos/seed/aqualedger-ss2/1200/800",
        "https://picsum.photos/seed/aqualedger-ss3/1200/800"
      ]
    }
  },
  {
    id: 3,
    title: "Envision College Event Website",
    thumbnail: "https://i.ibb.co/TD8n386m/New-Project-3.png",
    description: "A sleek, modern marketing website designed to capture leads, with animations powered by Framer Motion.",
    stack: ["React", "Framer Motion", "UI/UX"],
    liveDemoUrl: "#",
    codeUrl: "#",
    caseStudy: {
      problem: "A startup needed a visually appealing landing page that could clearly communicate its value proposition and convert visitors into leads.",
      solution: "A user-centric design process was followed to create an intuitive layout. The site was built in React, with subtle, engaging animations from Framer Motion to guide the user's attention. A Formspree-integrated contact form was included for lead capture.",
      role: "Lead designer and front-end developer responsible for design, development, and deployment.",
      impact: "The new design led to a 40% increase in user engagement and a 25% higher conversion rate on the contact form.",
      screenshots: [
        "https://picsum.photos/seed/gamma-ss1/1200/800"
      ]
    }
  },
  {
    id: 5,
    title: "WebP Wizard",
    thumbnail: "/projects/webpwizard/WebpWizardCover.webp",
    description:
      "WebP Wizard is a tool designed to make image conversion to WebP format simple, fast, and efficient. With newly added AI-powered alt text generator, WebP Wizard not only compresses images but intelligently optimizes them for quality and content—helping you deliver the best visuals with the smallest files.",
    stack: [
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "AI/ML",
      "Image Processing",
      "WebP Conversion",
      "Alt Text Generation",
      "Optimization Algorithms"
    ],
    liveDemoUrl: "https://webpwizard.manishshetty.dev/",
    codeUrl: "https://github.com/ManishRShetty/webp-wizard",
    caseStudy: {
      problem:
        "Web developers face challenges in optimizing images for web performance while maintaining quality. Manual image compression is time-consuming, and generating meaningful alt text for accessibility requires significant effort and expertise.",
      solution:
        "Built WebP Wizard with intelligent image conversion algorithms that automatically optimize images for the web while preserving visual quality. Integrated AI-powered alt text generation to enhance web accessibility by automatically creating descriptive, contextually relevant alternative text for images.",
      role:
        "Developed the complete tool including the image conversion engine, AI model integration for alt text generation, optimization algorithms, and user interface for seamless interaction.",
      impact:
        "Significantly reduced image file sizes while maintaining quality, improved web performance through efficient WebP conversion, and enhanced accessibility by automatically generating meaningful alt text. Streamlined the workflow for web developers by combining compression and accessibility features in one tool.",
      screenshots: [
        "/projects/webpwizard/Screenshot1.webp",
        "/projects/webpwizard/Screenshot2.webp",
        "/projects/webpwizard/Screenshot3.webp"
      ]
    }
  }
];
